# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import utils
import pymysql

db = pymysql.connect(host='localhost',
                     port=3306,
                     user='root',
                     passwd='123456',
                     db='exp3',
                     charset='utf8')

class Ui_usermain(object):
    def setupUi(self, MainWindow, main_window, stu_id, username, password):
        self.main_window = main_window
        self.current_window = MainWindow
        self.stu_id = stu_id
        self.username = username
        self.password = password
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 1094)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(950, 110, 20, 831))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(260, 930, 701, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 140, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(440, 280, 391, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 100, 701, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(250, 110, 20, 831))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 建立联系
        self.pushButton_3.clicked.connect(self.back)
        self.pushButton_2.clicked.connect(self.search)
        self.pushButton_5.clicked.connect(self.search_unreturned)
        self.pushButton.clicked.connect(self.borrow)
        self.pushButton_4.clicked.connect(self.return_book)

    def return_book(self):
        db.commit()
        from return_book import Ui_return_book
        self.return_book_window = QtWidgets.QMainWindow()
        self.ui = Ui_return_book()
        self.ui.setupUi(self.return_book_window, self.current_window, self.stu_id, self.username, self.password)
        self.return_book_window.show()
        self.current_window.close()

    def borrow(self):
        db.commit()
        from borrow import Ui_borrow
        self.borrow_window = QtWidgets.QMainWindow()
        self.ui = Ui_borrow()
        self.ui.setupUi(self.borrow_window, self.current_window, self.stu_id, self.username, self.password)
        self.borrow_window.show()
        self.current_window.close()

    def back(self):
        self.main_window.show()
        self.current_window.close()

    def search_unreturned(self):
        db.commit()
        student = utils.Student(self.stu_id[0], self.username, self.password)
        result = student.show_borrowed_books(db)
        from search_unreturned import Ui_search_unreturned
        self.search_unreturned_window = QtWidgets.QMainWindow()
        self.ui = Ui_search_unreturned()
        self.ui.setupUi(self.search_unreturned_window, self.current_window, result)
        self.search_unreturned_window.show()
        self.current_window.close()

    def search(self):
        from search import Ui_search
        self.search_window = QtWidgets.QMainWindow()
        self.ui = Ui_search()
        self.ui.setupUi(self.search_window, self.current_window, self.get_books())
        self.search_window.show()
        self.current_window.close()

    def get_books(self):
        cur = db.cursor()
        cur.execute("SELECT * FROM book")
        result = cur.fetchall()
        cur.close()
        return result

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "用户操作界面"))
        self.pushButton.setText(_translate("MainWindow", "借阅书籍"))
        self.pushButton_4.setText(_translate("MainWindow", "归还书籍"))
        self.pushButton_2.setText(_translate("MainWindow", "查询书籍"))
        self.pushButton_5.setText(_translate("MainWindow", "查询待归还的书籍"))
        self.pushButton_3.setText(_translate("MainWindow", "返回"))

# 在本模块内测试
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    main_window = QtWidgets.QMainWindow()  # 假设这是你的主窗口

    # 模拟用户登录信息
    stu_id = 1
    username = '张三'
    password = 'password'

    ui = Ui_usermain()
    ui.setupUi(MainWindow, main_window, stu_id, username, password)
    MainWindow.show()
    sys.exit(app.exec_())
